import { WorkerResultSchema } from "./schemas.js";
import type { RepoOpsAdapter, WorkerModule, WorkerResult, WorkerTaskPacket } from "./types.js";
import { REPO_OPERATION_IDS } from "./constants.js";

export type WorkerExecutor = (task: WorkerTaskPacket, repoOps: RepoOpsAdapter) => Promise<WorkerResult>;

function estimateChangedLoc(result: WorkerResult): number {
  let total = 0;
  for (const change of result.proposedChanges) {
    if (change.startLine && change.endLine) {
      total += Math.max(1, change.endLine - change.startLine + 1);
    } else {
      total += 20;
    }
  }
  return total;
}

export class BoundedWorkerModule implements WorkerModule {
  constructor(
    private readonly repoOps: RepoOpsAdapter,
    private readonly executor?: WorkerExecutor,
  ) {}

  async execute(task: WorkerTaskPacket): Promise<WorkerResult> {
    const initial: WorkerResult = this.executor
      ? await this.executor(task, this.repoOps)
      : {
          summary: "No-op worker result generated by bounded worker fallback.",
          proposedChanges: [],
          touchedFiles: [],
          evidence: [],
          unresolvedIssues: [],
          confidence: 0.5,
          needsHumanInput: false,
        };

    const normalized = WorkerResultSchema.parse(initial);
    if (typeof normalized.tokensUsed === "number" && normalized.tokensUsed > task.tokenBudget) {
      return {
        ...normalized,
        unresolvedIssues: [...normalized.unresolvedIssues, `token_budget_exceeded:${normalized.tokensUsed}>${task.tokenBudget}`],
        needsHumanInput: true,
        confidence: Math.min(normalized.confidence, 0.4),
      };
    }
    if (typeof normalized.stepsUsed === "number" && normalized.stepsUsed > task.stepBudget) {
      return {
        ...normalized,
        unresolvedIssues: [...normalized.unresolvedIssues, `step_budget_exceeded:${normalized.stepsUsed}>${task.stepBudget}`],
        needsHumanInput: true,
        confidence: Math.min(normalized.confidence, 0.4),
      };
    }
    const locEstimate = estimateChangedLoc(normalized);
    if (locEstimate > task.locBudget) {
      return {
        ...normalized,
        unresolvedIssues: [...normalized.unresolvedIssues, `loc_budget_exceeded:${locEstimate}>${task.locBudget}`],
        needsHumanInput: true,
        confidence: Math.min(normalized.confidence, 0.4),
      };
    }
    if (normalized.touchedFiles.some((f) => task.forbiddenFiles.includes(f))) {
      return {
        ...normalized,
        unresolvedIssues: [...normalized.unresolvedIssues, "forbidden_file_touched"],
        needsHumanInput: true,
        confidence: Math.min(normalized.confidence, 0.4),
      };
    }
    const enforceValidation = (process.env.SYNESIS_YARN_ORCHESTRATION_ENFORCE_VALIDATION ?? "false").toLowerCase() === "true";
    if (enforceValidation && task.requiredValidation.includes("run_lint")) {
      const lintRes = await this.repoOps.call({ op: REPO_OPERATION_IDS.runLint, args: {} });
      if (!lintRes.ok) {
        return {
          ...normalized,
          unresolvedIssues: [...normalized.unresolvedIssues, "required_validation_failed:run_lint"],
          needsHumanInput: true,
          confidence: Math.min(normalized.confidence, 0.4),
        };
      }
    }
    return normalized;
  }
}
