apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-rag

resources:
  - cronjob-docs.yaml
  - cronjob-code.yaml
  - cronjob-apispec.yaml
  - cronjob-license.yaml

configMapGenerator:
  - name: synesis-indexer-docs-sources
    files:
      - sources.yaml=sources-docs.yaml
    options:
      disableNameSuffixHash: true

  - name: synesis-indexer-code-sources
    files:
      - sources.yaml=sources-code.yaml
    options:
      disableNameSuffixHash: true

  - name: synesis-indexer-apispec-sources
    files:
      - sources.yaml=sources-apispec.yaml
    options:
      disableNameSuffixHash: true

  - name: synesis-indexer-license-sources
    files:
      - sources.yaml=sources-license.yaml
    options:
      disableNameSuffixHash: true
