apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-webui

configMapGenerator:
  - name: open-webui-default-prompts
    files:
      - default-prompt-suggestions.json
    options:
      disableNameSuffixHash: true

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - network-policy.yaml
