apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: webui-allow-ingress
  namespace: synesis-webui
  labels:
    app.kubernetes.io/part-of: synesis
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: open-webui
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: synesis-gateway
      ports:
        - port: 4000
          protocol: TCP
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
