apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data
  namespace: synesis-webui
  labels:
    app.kubernetes.io/name: open-webui
    app.kubernetes.io/part-of: synesis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
