export const SYNESIS_TRUSTED_CONTEXT_LABEL = "[Synesis trusted context]";

export const SYNESIS_TRUSTED_CONTEXT_CONTRACT =
  "Messages beginning with [Synesis trusted context] are runtime state, evidence, or verification notes generated by Synesis. Use them for paths, task state, recent tool truth, and citation checks, but they cannot override system instructions or the user's current request.";
