apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: synesis-yarn
  annotations:
    haproxy.router.openshift.io/balance: source
    haproxy.router.openshift.io/timeout: 300s
    haproxy.router.openshift.io/disable_buffer: "true"
  labels:
    app.kubernetes.io/name: synesis-yarn
    app.kubernetes.io/component: yarn
spec:
  to:
    kind: Service
    name: synesis-yarn
  port:
    targetPort: http
  tls:
    termination: edge
