name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement to Project Synesis!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? Why is it needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you considered?

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Planner (LangGraph)
        - Gateway (LiteLLM)
        - RAG Pipeline
        - Sandbox / Executor
        - LSP Gateway
        - Model Serving
        - Web UI
        - Knowledge Indexers
        - Observability
        - Deployment / DevOps
        - New Component
