apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synesis-rag

labels:
  - pairs:
      app.kubernetes.io/part-of: synesis
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false

resources:
  - namespace.yaml
  - milvus-operator.yaml
  - embedder/deployment.yaml
  - embedder/service.yaml
  - keyword-service/deployment.yaml
  - keyword-service/service.yaml
  - gliner-service/deployment.yaml
  - gliner-service/service.yaml
  - redis/pvc.yaml
  - redis/deployment.yaml
  - redis/service.yaml
