# Grant Milvus operator permission to create/get SCCs for MinIO/etcd.
# The Bitnami charts create an SCC (synesis-milvus-minio) for OpenShift;
# the operator's SA lacks this permission by default.
# Apply as cluster-admin: oc apply -f base/rag/milvus/milvus-operator-scc-rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvus-operator-scc
  labels:
    app.kubernetes.io/part-of: synesis
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: milvus-operator-scc
  labels:
    app.kubernetes.io/part-of: synesis
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: milvus-operator-scc
subjects:
  - kind: ServiceAccount
    name: milvus-operator
    namespace: milvus-operator
