# DataSciencePipelinesApplication — with static S3 credentials
# envsubst: DS_PROJECT, S3_BUCKET, S3_HOST, AWS_REGION, DSPA_NAME, S3_CREDENTIALS_SECRET
---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: ${DSPA_NAME}
  namespace: ${DS_PROJECT}
spec:
  dspVersion: v2
  apiServer:
    enableSamplePipeline: false
  objectStorage:
    externalStorage:
      bucket: ${S3_BUCKET}
      host: ${S3_HOST}
      region: ${AWS_REGION}
      scheme: https
      s3CredentialsSecret:
        accessKey: AWS_ACCESS_KEY_ID
        secretKey: AWS_SECRET_ACCESS_KEY
        secretName: ${S3_CREDENTIALS_SECRET}
