# DataSciencePipelinesApplication — Pipeline Server with S3 (IRSA, no keys)
# envsubst: DS_PROJECT, S3_BUCKET, S3_HOST, AWS_REGION, DSPA_NAME
---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: ${DSPA_NAME}
  namespace: ${DS_PROJECT}
spec:
  dspVersion: v2
  apiServer:
    enableSamplePipeline: false
  objectStorage:
    externalStorage:
      bucket: ${S3_BUCKET}
      host: ${S3_HOST}
      region: ${AWS_REGION}
      scheme: https
