# ODH URI connection for HuggingFace model
apiVersion: v1
kind: Secret
metadata:
  name: synesis-executor
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/display-name: Synesis Executor (Qwen3-Coder-Next)
type: Opaque
stringData:
  URI: "hf://Qwen/Qwen3-Coder-Next"