# RHOAI workaround (RHOAIENG-23169): register hf:// protocol support.
# Without this, the storage initializer doesn't know how to handle
# HuggingFace URIs and the model download fails.
#
# RHOAI's webhook already injects HF_HOME, HF_HUB_ENABLE_HF_TRANSFER,
# etc. into the init container. Do NOT set HF env vars here or they
# will conflict with the webhook-injected values.

apiVersion: serving.kserve.io/v1alpha1
kind: ClusterStorageContainer
metadata:
  name: hf-hub
spec:
  container:
    name: storage-initializer
    image: registry.redhat.io/rhoai/odh-kserve-storage-initializer-rhel9@sha256:17631a94bb410a662084480b710a3ceaad8e744b84f59f40f2db3c3ea39e45b4
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 4Gi
  supportedUriFormats:
    - prefix: "hf://"
