# STS/IRSA is the recommended approach for S3 access on OpenShift.
#
# When using STS roles, the pod's service account is annotated with an
# IAM role ARN and the AWS SDK automatically picks up temporary
# credentials via the projected token volume. No Secret needed.
#
# This file is kept as a fallback for environments without STS.
# To use it, uncomment the resource in kustomization.yaml and
# fill in the credentials below.
#
# For STS setup, annotate the service account instead:
#   oc annotate serviceaccount default \
#     -n synesis-models \
#     eks.amazonaws.com/role-arn=arn:aws:iam::ACCOUNT:role/synesis-model-reader
#
# Or for ROSA with STS:
#   oc annotate serviceaccount default \
#     -n synesis-models \
#     eks.amazonaws.com/role-arn=arn:aws:iam::ACCOUNT:role/synesis-model-reader

apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-synesis-models
  namespace: synesis-models
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
    app.kubernetes.io/part-of: synesis
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: Synesis Model Storage
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_ME"
  AWS_SECRET_ACCESS_KEY: "REPLACE_ME"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_S3_BUCKET: "byron-ai-4b0263a0-rhoai-data"
  AWS_S3_ENDPOINT: ""
