# KServe requires this Secret to exist so the admission webhook can
# determine storage type from the connection-type annotation.
# With STS/IRSA the actual credentials come from the service account's
# projected token -- the values here are intentionally empty.
#
# For non-STS environments, fill in AWS_ACCESS_KEY_ID and
# AWS_SECRET_ACCESS_KEY with real credentials.

apiVersion: v1
kind: Secret
metadata:
  name: aws-connection-synesis-models
  namespace: synesis-models
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
    app.kubernetes.io/part-of: synesis
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: Synesis Model Storage
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_S3_BUCKET: "byron-ai-4b0263a0-rhoai-data"
  AWS_S3_ENDPOINT: ""
