apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: qwen-coder-32b
  namespace: synesis-models
  annotations:
    opendatahub.io/accelerator-name: migrated-gpu
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/template-display-name: Synesis Qwen Coder vLLM Runtime
    opendatahub.io/template-name: synesis-qwen-coder-runtime
    openshift.io/display-name: Qwen 2.5 Coder 32B FP8
  labels:
    opendatahub.io/dashboard: "true"
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: model-serving
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - name: kserve-container
      # Upstream vLLM - public, stable. Override via kustomize for registry.redhat.io/rhaiis/vllm-cuda-rhel9 if preferred.
      image: vllm/vllm-openai:latest
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
        - --dtype=float16
        - --quantization=fp8
        - --max-model-len=16384
        - --gpu-memory-utilization=0.90
        - --distributed-executor-backend=mp
        - --enforce-eager
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        limits:
          cpu: "8"
          memory: 48Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "4"
          memory: 32Gi
          nvidia.com/gpu: "1"
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
