# ServingRuntime for synesis-summarizer — vLLM CUDA, Qwen2.5-0.5B-Instruct.
# GPU: ~1–2GB VRAM. Enables speculative decoding when colocated; standalone for summarizer API.
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: synesis-summarizer
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-name: vllm-cuda-runtime-template
    openshift.io/display-name: Synesis Summarizer (vLLM CUDA, 0.5B)
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
        - --tensor-parallel-size=1
        - --max-model-len=8192
        - --gpu-memory-utilization=0.5
        - --trust-remote-code
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:094db84a1da5e8a575d0c9eade114fa30f4a2061064a338e3e032f3578f8082a
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
