# ServingRuntime for synesis-executor — vLLM CUDA for Qwen3-Coder-30B-A3B-FP8 (30B MoE, ~30GB FP8).
# Args from vLLM recipes: https://docs.vllm.ai/projects/recipes/en/latest/Qwen/Qwen3-Coder-480B-A35B.html
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: synesis-executor
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    opendatahub.io/serving-runtime-scope: global
    opendatahub.io/template-name: vllm-cuda-runtime-template
    openshift.io/display-name: Synesis Executor (vLLM CUDA)
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
    - args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name={{.Name}}
        - --tensor-parallel-size=1
        - --max-model-len=32768
        - --speculative_config
        - '{"method": "ngram", "num_speculative_tokens": 5, "prompt_lookup_max": 4}'
        - --reasoning-parser=qwen3
        - --enable-auto-tool-choice
        - --tool-call-parser=qwen3_coder
        - --gpu-memory-utilization=0.9
        - --no-enable-prefix-caching
        - --trust-remote-code
      command:
        - python
        - -m
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:094db84a1da5e8a575d0c9eade114fa30f4a2061064a338e3e032f3578f8082a
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
