apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-data
  namespace: synesis-opik
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: opik-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
