apiVersion: v1
kind: Service
metadata:
  name: opik-frontend
  namespace: synesis-opik
  labels:
    app.kubernetes.io/name: opik-frontend
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: opik
spec:
  selector:
    app.kubernetes.io/name: opik-frontend
  ports:
    - name: http
      port: 5173
      targetPort: http
