apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: synesis-opik
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: opik-cache
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
