apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: synesis-opik
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: synesis
    app.kubernetes.io/component: opik-storage
spec:
  selector:
    app.kubernetes.io/name: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: client
