spdx:
  licenses_url: "https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json"
  details_base_url: "https://raw.githubusercontent.com/spdx/license-list-data/master/json/details/"

fedora:
  repo_url: "https://gitlab.com/fedora/legal/fedora-license-data/-/raw/main/data/"
  common_licenses:
    - "0BSD"
    - "AAL"
    - "AFL-3.0"
    - "AGPL-3.0-only"
    - "AGPL-3.0-or-later"
    - "Apache-2.0"
    - "Artistic-2.0"
    - "BSD-2-Clause"
    - "BSD-3-Clause"
    - "BSL-1.0"
    - "CC-BY-4.0"
    - "CC-BY-SA-4.0"
    - "CC0-1.0"
    - "CDDL-1.0"
    - "CPL-1.0"
    - "ECL-2.0"
    - "EPL-1.0"
    - "EPL-2.0"
    - "EUPL-1.2"
    - "GPL-2.0-only"
    - "GPL-2.0-or-later"
    - "GPL-3.0-only"
    - "GPL-3.0-or-later"
    - "ISC"
    - "LGPL-2.1-only"
    - "LGPL-2.1-or-later"
    - "LGPL-3.0-only"
    - "LGPL-3.0-or-later"
    - "MIT"
    - "MIT-0"
    - "MPL-2.0"
    - "MS-PL"
    - "MS-RL"
    - "MulanPSL-2.0"
    - "NCSA"
    - "OFL-1.1"
    - "OSL-3.0"
    - "PostgreSQL"
    - "PSF-2.0"
    - "Unlicense"
    - "UPL-1.0"
    - "W3C"
    - "Zlib"

choosealicense:
  repo: "github/choosealicense.com"
  branch: "gh-pages"
  licenses_path: "_licenses"
