import { describe, expect, it } from "vitest";
import { buildScopePredicate, addScopeParams } from "../src/retrieval/rag-client.js";
import type { ScopeFilterOptions } from "../src/retrieval/types.js";

/**
 * Evaluates a generated Cypher scope predicate against a simulated content
 * node's properties. This is a simplified JS-side evaluator that mirrors the
 * semantics of the Cypher clauses generated by buildScopePredicate.
 *
 * Returns true if the content would pass the predicate (visible to caller).
 */
function evaluatePredicate(
  predicate: string,
  params: Record<string, unknown>,
  content: {
    visibility_scope?: string;
    org_id?: string;
    tenant_id?: string;
    owner_user_id?: string;
    conversation_id?: string;
    expires_at_epoch?: number;
    acl_mode?: string;
    acl_groups?: string;
    acl_group_ids?: string[];
  },
): boolean {
  const vs = content.visibility_scope ?? "global";
  const orgId = content.org_id ?? "";
  const tenantId = content.tenant_id ?? "";
  const ownerId = content.owner_user_id ?? "";
  const convId = content.conversation_id ?? "";
  const expiresAt = content.expires_at_epoch ?? 0;
  const aclMode = content.acl_mode ?? "open";
  const aclGroupIds = content.acl_group_ids ?? [];
  const aclGroupsCsv = content.acl_groups ?? "";

  const callerOrgId = params.caller_org_id as string | undefined;
  const callerTenantIds = (params.caller_tenant_ids ?? []) as string[];
  const callerAclGroups = (params.caller_acl_groups ?? []) as string[];
  const callerUserId = params.caller_user_id as string | undefined;
  const callerConvId = params.caller_conversation_id as string | undefined;
  const nowEpoch = (params.now_epoch ?? 0) as number;

  // Visibility tier check (OR)
  let visibilityPassed = false;
  if (vs === "global" || vs === "") visibilityPassed = true;
  if (vs === "org" && callerOrgId && orgId === callerOrgId) visibilityPassed = true;
  if (vs === "tenant" && callerOrgId && orgId === callerOrgId && callerTenantIds.includes(tenantId)) visibilityPassed = true;
  if (vs === "user" && callerOrgId && orgId === callerOrgId && callerUserId && ownerId === callerUserId) visibilityPassed = true;
  if (vs === "session" && callerOrgId && orgId === callerOrgId && callerUserId && ownerId === callerUserId && callerConvId && convId === callerConvId) {
    if (expiresAt <= 0 || expiresAt >= nowEpoch) visibilityPassed = true;
  }

  if (!visibilityPassed) return false;

  // ACL check (AND with visibility)
  const isEnforce = predicate.includes('"restricted", "private"');
  if (isEnforce) return true; // enforce mode widens to let FGA decide

  if (callerAclGroups.length > 0) {
    if (aclMode === "" || aclMode === "open") return true;
    const csvGroups = aclGroupsCsv.split(",").map((g) => g.trim()).filter(Boolean);
    const allContentGroups = [...new Set([...aclGroupIds, ...csvGroups])];
    return callerAclGroups.some((g) => allContentGroups.includes(g));
  }

  return aclMode === "" || aclMode === "open";
}

describe("buildScopePredicate — exhaustive matrix", () => {
  type MatrixCase = [
    string,
    ScopeFilterOptions | undefined,
    {
      visibility_scope?: string;
      org_id?: string;
      tenant_id?: string;
      owner_user_id?: string;
      conversation_id?: string;
      expires_at_epoch?: number;
      acl_mode?: string;
      acl_groups?: string;
      acl_group_ids?: string[];
    },
    boolean,
  ];

  const cases: MatrixCase[] = [
    // --- Global tier ---
    ["no scope -> global+open = ALLOW", undefined, { visibility_scope: "global", acl_mode: "open" }, true],
    ["empty scope -> global+open = ALLOW", {}, { visibility_scope: "global", acl_mode: "open" }, true],
    ["no scope -> global+restricted = DENY", undefined, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "eng" }, false],
    ["no scope -> org scoped = DENY", undefined, { visibility_scope: "org", org_id: "acme", acl_mode: "open" }, false],

    // --- Org tier ---
    ["org=acme -> org+acme+open = ALLOW", { callerOrgId: "acme" }, { visibility_scope: "org", org_id: "acme", acl_mode: "open" }, true],
    ["org=acme -> org+other+open = DENY", { callerOrgId: "acme" }, { visibility_scope: "org", org_id: "other", acl_mode: "open" }, false],
    ["org=acme -> global+open = ALLOW", { callerOrgId: "acme" }, { visibility_scope: "global", acl_mode: "open" }, true],
    ["no org -> org+acme = DENY", {}, { visibility_scope: "org", org_id: "acme", acl_mode: "open" }, false],

    // --- Tenant tier ---
    ["org+tenant=t1 -> tenant+acme+t1+open = ALLOW", { callerOrgId: "acme", callerTenantIds: ["t1"] }, { visibility_scope: "tenant", org_id: "acme", tenant_id: "t1", acl_mode: "open" }, true],
    ["org+tenant=t1 -> tenant+acme+t2+open = DENY", { callerOrgId: "acme", callerTenantIds: ["t1"] }, { visibility_scope: "tenant", org_id: "acme", tenant_id: "t2", acl_mode: "open" }, false],
    ["org+tenant=t1 -> tenant+other+t1+open = DENY", { callerOrgId: "acme", callerTenantIds: ["t1"] }, { visibility_scope: "tenant", org_id: "other", tenant_id: "t1", acl_mode: "open" }, false],
    ["org only -> tenant+acme+t1 = DENY", { callerOrgId: "acme" }, { visibility_scope: "tenant", org_id: "acme", tenant_id: "t1", acl_mode: "open" }, false],
    ["multi-tenant [t1,t2] -> t2 = ALLOW", { callerOrgId: "acme", callerTenantIds: ["t1", "t2"] }, { visibility_scope: "tenant", org_id: "acme", tenant_id: "t2", acl_mode: "open" }, true],
    ["multi-tenant [t1,t2] -> t3 = DENY", { callerOrgId: "acme", callerTenantIds: ["t1", "t2"] }, { visibility_scope: "tenant", org_id: "acme", tenant_id: "t3", acl_mode: "open" }, false],

    // --- User tier ---
    ["org+user=alice -> user+acme+alice+open = ALLOW", { callerOrgId: "acme", callerUserId: "alice" }, { visibility_scope: "user", org_id: "acme", owner_user_id: "alice", acl_mode: "open" }, true],
    ["org+user=alice -> user+acme+bob+open = DENY", { callerOrgId: "acme", callerUserId: "alice" }, { visibility_scope: "user", org_id: "acme", owner_user_id: "bob", acl_mode: "open" }, false],
    ["org+user=alice -> user+other+alice+open = DENY", { callerOrgId: "acme", callerUserId: "alice" }, { visibility_scope: "user", org_id: "other", owner_user_id: "alice", acl_mode: "open" }, false],
    ["org only -> user+acme+alice = DENY", { callerOrgId: "acme" }, { visibility_scope: "user", org_id: "acme", owner_user_id: "alice", acl_mode: "open" }, false],

    // --- Session tier ---
    ["full ctx -> session+matching+not-expired = ALLOW", { callerOrgId: "acme", callerUserId: "alice", callerConversationId: "c1" }, { visibility_scope: "session", org_id: "acme", owner_user_id: "alice", conversation_id: "c1", expires_at_epoch: 0, acl_mode: "open" }, true],
    ["full ctx -> session+wrong conv = DENY", { callerOrgId: "acme", callerUserId: "alice", callerConversationId: "c1" }, { visibility_scope: "session", org_id: "acme", owner_user_id: "alice", conversation_id: "c2", expires_at_epoch: 0, acl_mode: "open" }, false],
    ["full ctx -> session+expired = DENY", { callerOrgId: "acme", callerUserId: "alice", callerConversationId: "c1" }, { visibility_scope: "session", org_id: "acme", owner_user_id: "alice", conversation_id: "c1", expires_at_epoch: 1, acl_mode: "open" }, false],
    ["full ctx -> session+far-future expiry = ALLOW", { callerOrgId: "acme", callerUserId: "alice", callerConversationId: "c1" }, { visibility_scope: "session", org_id: "acme", owner_user_id: "alice", conversation_id: "c1", expires_at_epoch: 9999999999, acl_mode: "open" }, true],
    ["no conv -> session = DENY", { callerOrgId: "acme", callerUserId: "alice" }, { visibility_scope: "session", org_id: "acme", owner_user_id: "alice", conversation_id: "c1", expires_at_epoch: 0, acl_mode: "open" }, false],
    ["wrong user -> session = DENY", { callerOrgId: "acme", callerUserId: "bob", callerConversationId: "c1" }, { visibility_scope: "session", org_id: "acme", owner_user_id: "alice", conversation_id: "c1", expires_at_epoch: 0, acl_mode: "open" }, false],

    // --- ACL enforcement ---
    ["no groups -> restricted = DENY", { callerOrgId: "acme" }, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "eng", acl_group_ids: ["eng"] }, false],
    ["no groups -> private = DENY", { callerOrgId: "acme" }, { visibility_scope: "global", acl_mode: "private", acl_groups: "eng", acl_group_ids: ["eng"] }, false],
    ["groups=[eng] -> restricted+eng = ALLOW", { callerOrgId: "acme", callerAclGroups: ["eng"] }, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "eng", acl_group_ids: ["eng"] }, true],
    ["groups=[eng] -> restricted+sales = DENY", { callerOrgId: "acme", callerAclGroups: ["eng"] }, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "sales", acl_group_ids: ["sales"] }, false],
    ["groups=[eng] -> open = ALLOW", { callerOrgId: "acme", callerAclGroups: ["eng"] }, { visibility_scope: "global", acl_mode: "open" }, true],
    ["groups=[eng,sales] -> restricted+sales = ALLOW", { callerOrgId: "acme", callerAclGroups: ["eng", "sales"] }, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "sales", acl_group_ids: ["sales"] }, true],
    ["CSV acl_groups match via acl_group_ids", { callerOrgId: "acme", callerAclGroups: ["team-beta"] }, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "team-alpha, team-beta", acl_group_ids: ["team-alpha", "team-beta"] }, true],

    // --- Enforce mode (widens ACL for FGA) ---
    ["enforce+user -> private = ALLOW (FGA decides)", { callerOrgId: "acme", callerUserId: "alice", authzMode: "enforce" }, { visibility_scope: "global", acl_mode: "private", acl_groups: "eng", acl_group_ids: ["eng"] }, true],
    ["enforce+user -> restricted = ALLOW (FGA decides)", { callerOrgId: "acme", callerUserId: "alice", authzMode: "enforce" }, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "eng", acl_group_ids: ["eng"] }, true],
    ["enforce WITHOUT user -> private = DENY", { callerOrgId: "acme", authzMode: "enforce" }, { visibility_scope: "global", acl_mode: "private", acl_groups: "eng", acl_group_ids: ["eng"] }, false],

    // --- Edge: missing/empty scope defaults ---
    ["empty vis_scope defaults to global", { callerOrgId: "acme" }, { visibility_scope: "", acl_mode: "open" }, true],
    ["missing vis_scope defaults to global", { callerOrgId: "acme" }, { acl_mode: "open" }, true],
    ["empty acl_mode defaults to open", { callerOrgId: "acme" }, { visibility_scope: "global", acl_mode: "" }, true],
    ["missing acl_mode defaults to open", { callerOrgId: "acme" }, { visibility_scope: "global" }, true],

    // --- Solo user (no org) ---
    ["solo user -> org content = DENY", { callerUserId: "alice" }, { visibility_scope: "org", org_id: "acme", acl_mode: "open" }, false],
    ["solo user -> global+open = ALLOW", { callerUserId: "alice" }, { visibility_scope: "global", acl_mode: "open" }, true],
    ["solo user -> global+restricted = DENY", { callerUserId: "alice" }, { visibility_scope: "global", acl_mode: "restricted", acl_groups: "eng" }, false],
  ];

  it.each(cases)("%s", (_label, scope, content, expectedAllow) => {
    const alias = "n";
    const predicate = buildScopePredicate(alias, scope);
    const params: Record<string, unknown> = {};
    addScopeParams(scope, params);

    const result = evaluatePredicate(predicate, params, content);
    expect(result).toBe(expectedAllow);
  });
});

describe("buildScopePredicate — structural assertions", () => {
  it("always starts with global visibility clause", () => {
    const pred = buildScopePredicate("n", { callerOrgId: "x" });
    expect(pred).toMatch(/^\(\(coalesce\(n\.visibility_scope, "global"\) = "global"/);
  });

  it("all visibility clauses are OR-combined", () => {
    const pred = buildScopePredicate("n", {
      callerOrgId: "acme",
      callerTenantIds: ["t1"],
      callerUserId: "alice",
      callerConversationId: "c1",
    });
    const orCount = (pred.match(/ OR /g) ?? []).length;
    expect(orCount).toBeGreaterThanOrEqual(4);
  });

  it("ACL clause is AND-combined with visibility", () => {
    const pred = buildScopePredicate("n", { callerOrgId: "acme" });
    expect(pred).toContain(") AND coalesce(n.acl_mode");
  });

  it("uses parameterized $caller_org_id, not inlined value", () => {
    const pred = buildScopePredicate("n", { callerOrgId: "acme" });
    expect(pred).toContain("$caller_org_id");
    expect(pred).not.toContain('"acme"');
  });

  it("uses parameterized $caller_tenant_ids, not inlined values", () => {
    const pred = buildScopePredicate("n", { callerOrgId: "acme", callerTenantIds: ["t1"] });
    expect(pred).toContain("$caller_tenant_ids");
    expect(pred).not.toContain('"t1"');
  });

  it("uses parameterized $caller_user_id, not inlined value", () => {
    const pred = buildScopePredicate("n", { callerOrgId: "acme", callerUserId: "alice" });
    expect(pred).toContain("$caller_user_id");
    expect(pred).not.toContain('"alice"');
  });

  it("supports the known diagnostic alias", () => {
    const pred = buildScopePredicate("n", { callerOrgId: "acme" });
    expect(pred).toContain("n.visibility_scope");
    expect(pred).toContain("n.org_id");
    expect(pred).not.toContain("node.");
    expect(pred).not.toContain("neighbor.");
  });

  it("rejects unknown alias names", () => {
    expect(() => buildScopePredicate("myAlias", { callerOrgId: "acme" })).toThrow(
      "invalid_scope_predicate_alias:myAlias",
    );
    expect(() => buildScopePredicate("node) OR true //", { callerOrgId: "acme" })).toThrow(
      "invalid_scope_predicate_alias:node) OR true //",
    );
  });
});

describe("addScopeParams — parameter binding", () => {
  it("binds all scope fields when fully populated", () => {
    const params: Record<string, unknown> = {};
    addScopeParams({
      callerOrgId: "acme",
      callerTenantIds: ["t1", "t2"],
      callerAclGroups: ["eng"],
      callerUserId: "alice",
      callerConversationId: "conv-1",
    }, params);
    expect(params).toMatchObject({
      caller_org_id: "acme",
      caller_tenant_ids: ["t1", "t2"],
      caller_acl_groups: ["eng"],
      caller_user_id: "alice",
      caller_conversation_id: "conv-1",
    });
    expect(typeof params.now_epoch).toBe("number");
  });

  it("binds nothing when scope is undefined", () => {
    const params: Record<string, unknown> = {};
    addScopeParams(undefined, params);
    expect(Object.keys(params)).toHaveLength(0);
  });

  it("binds nothing when scope is empty", () => {
    const params: Record<string, unknown> = {};
    addScopeParams({}, params);
    expect(Object.keys(params)).toHaveLength(0);
  });

  it("omits callerTenantIds when empty array", () => {
    const params: Record<string, unknown> = {};
    addScopeParams({ callerOrgId: "acme", callerTenantIds: [] }, params);
    expect(params.caller_tenant_ids).toBeUndefined();
  });

  it("sets now_epoch only when callerConversationId is present", () => {
    const withConv: Record<string, unknown> = {};
    addScopeParams({ callerOrgId: "a", callerUserId: "b", callerConversationId: "c" }, withConv);
    expect(withConv.now_epoch).toBeDefined();

    const withoutConv: Record<string, unknown> = {};
    addScopeParams({ callerOrgId: "a", callerUserId: "b" }, withoutConv);
    expect(withoutConv.now_epoch).toBeUndefined();
  });
});
