apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: synesis-auth

resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - keycloak.yaml
  - realm-configmap.yaml
  - realm-import.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/part-of: synesis
